name: lfd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - arviz
  - pip
  - pip:
      - corner
      - emcee
      - watermark
