name: 2025-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nb_conda_kernels
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyterlab
  - ipykernel         
  - scikit-learn
  - arviz
  - emcee
  - ptemcee
  - zeus-mcmc
  - corner
  - emcee
  - pip
  - pip:
       - watermark
       - gpy
       - gpyopt
       - pymc
       - pocomc
